fern/versions/public.yml

Preview: https://devrev-preview-d649a521-362c-44a6-a00b-f8736f0821d7.docs.buildwithfern.com/

sidebar reorganization

---

fern/docs/pages/best_practices.mdx
fern/docs/pages/concepts.mdx
fern/docs/pages/create-accounts.mdx
fern/docs/pages/debugging.mdx
fern/docs/pages/developer-intro.mdx
fern/docs/pages/examples/samples.mdx
fern/docs/pages/limits.mdx
fern/docs/pages/upgrades.mdx
fern/docs/pages/versioning.mdx
fern/versions/public.yml

https://app.devrev.ai/devrev/works/ISS-84092

post-launch cosmetic items

---

fern/docs/pages/entities.mdx
fern/docs/pages/start.mdx
fern/docs/pages/welcome.mdx

https://app.devrev.ai/devrev/works/ISS-84365

messaging and navigation updates

---

fern/docs/pages/entities.mdx

https://app.devrev.ai/devrev/works/ISS-84365

messaging for entities

---

.gitignore
fern/docs/pages/references/keyrings.mdx

This pull request updates the keyring documentation for snap-ins to include comprehensive information about dynamic connections.
- Refactoring keyrings content
- Added content on developer_keyring
- Added content on keyring_types (dynamic connection)
Note: lot of content need to be added/changed

Updating keyring docs

---

fern/apis/beta/openapi/openapi-beta-latest.yaml
fern/apis/public/openapi/openapi-public.yaml

update API specs

---

fern/apis/beta/openapi-beta.yaml
fern/apis/public/openapi-public.yaml

chore: Update OpenAPI specifications to fix fern versioning

---

fern/apis/beta/openapi-beta.yaml
fern/apis/public/openapi-public.yaml

chore: Update OpenAPI specs

---

custom-implementation/package.json
custom-implementation/src/modules/sanity/schema.ts

update: package.json and schema.ts

---

fern/docs.yml
fern/docs/pages/plug-sdk/sdk-intro.mdx

no-work-item
https://devrev.slack.com/archives/C034XDC9Q8Y/p1733939250364309

fix mobile SDK references

---

.github/workflows/ekline.yml

run EkLine on all PRs

---

fern/docs.yml
fern/fern.config.json

no-work-item
https://devrev.slack.com/archives/C04RC3XE0G7/p1734541720026909?thread_ts=1733372557.744649&cid=C04RC3XE0G7

add Google Tag Manager

---

fern/fern.config.json

Reverts devrev/fern-api-docs#150

Revert ":herb: :sparkles: [Scheduled] Upgrade Fern CLI"

---

fern/docs.yml

redirect for snapin-development

---

fern/docs.yml

redirect sub-paths

---

fern/apis/beta/changelog/2025-04-02.md
fern/apis/beta/openapi-beta.yaml
fern/apis/public/changelog/2025-04-02.md
fern/apis/public/openapi-public.yaml

Picks some improved naming for SLA endpoints.

chore: Update OpenAPI specs (again)

---

fern/docs.yml

fixed redirects

---

fern/fern.config.json

This PR handles optional refs in the API reference.

handle optional refs

---

fern/docs/pages/snapin-concepts.mdx

Changed the paragraph describing publication of restricted marketplace items as private marketplaces have been deprecated.
https://app.devrev.ai/devrev/works/ISS-175257

ISS-175257: Fix outdated marketplace docs

---

fern/docs/pages/airdrop/supported-object-types.mdx

Work: https://app.devrev.ai/devrev/works/ISS-180330
Update the supported objects for Airdrop

Update supported objects for Airdrop

---

fern/docs/pages/airdrop/initial-domain-mapping.mdx

This removes duplicate text introduced when I was resolving conflicts.
https://app.devrev.ai/devrev/works/ISS-182709

fix: Duplicate text during merge

---

custom-implementation/src/components/footer.css
custom-implementation/src/components/header.css
custom-implementation/src/main.css
custom-implementation/src/main.tsx
fern/docs.yml

One last change when testing out the spacing for header and footer - needs to be tested on new fern frontend.
Purpose of this PR is to use the github action preview link to circumvent the issue with import '@devrev/marketing-shared-components/dist/cjs/index.css' when developing locally

Testing header footer

---

fern/docs/pages/airdrop/initial-domain-mapping.mdx
fern/docs/pages/airdrop/mcp.mdx
fern/docs/pages/airdrop/metadata-extraction.mdx

This PR:
- Removes mention of a reverse flag in chef cli
- Fixes MCP documentation callout
https://app.devrev.ai/devrev/works/ISS-188687

docs: Remove chef reverse flag

---

fern/docs/pages/sdks/web/user-identity.mdx

https://app.devrev.ai/devrev/works/ISS-162925

chore: Fix attribute table formatting in Plug documentation

---

fern/docs/pages/sdks/web/ue-migration.mdx

A few fixes in the UE to PLuG web SDK migration doc
https://app.devrev.ai/devrev/works/ISS-191902

chore: update plug web sdk migration doc
