- fern/fern.config.json
In this PR, we upgrade the Fern CLI to the latest version (0.16.27). As part of this upgrade there are bug fixes that will register common properties in a `oneOf`.
> fix: all union properties are shown

- fern/docs/pages/adaas/attachments-extraction.mdx
The previous example was incorrect, this commit fixes it.
no-work-item
> fix: Update ADaaS artifacts example

- .github/workflows/ekline.yml
- fern/docs/pages/plug-sdk/methods.mdx
https://app.devrev.ai/devrev/works/ISS-114135
> Enable EkLine in repo

- fern/docs/pages/start.mdx
Removing `| jq .` when creating snap-in version since it messes up the interactive interface when providing developer connections
> chore: nit fix when creating snap-in version

- fern/docs/pages/entities/webhooks.mdx
no-work-item
Fixed link target.
> link to webhooks page

- fern/docs/pages/plug-sdk/identify-web-user.mdx
- fern/docs/pages/plug-sdk/search-install.mdx
- fern/docs/pages/plug-sdk/track-events.mdx
- fern/docs/pages/plug-sdk/web-sdk-install.mdx
- fern/versions/public.yml
> PLuG Web SDK.mdx

- fern/docs/pages/custom-objects.mdx
- fern/versions/beta.yml
https://app.devrev.ai/devrev/works/ISS-121317
The PR will be ready for review as soon as the custom object APIs are beta (in-progress) ✅
> docs: add custom objects beta API documentation

- fern/docs/pages/references/snap-components.mdx
- fern/versions/public.yml
Adding snap components page in developer docs.
> chore: add Snap Components page

- .github/workflows/ekline.yml
- .github/workflows/oasdiff.yml
- .gitignore
Fix trigger to run on all PRs.
> GitHub actions

- fern/docs.yml
- fern/fern.config.json
Same thing as https://github.com/devrev/fern-api-docs/pull/133 but setting the `version` properly to make sure CLI handles the new config data.
To use the `gtm` key, need to make sure version >= 0.46.22 where we added support
> Configure Google Tag Manager in docs.yml

- custom-implementation/src/main.css
- custom-implementation/src/main.tsx
> fix: mobile header css

- fern/docs/pages/retry-mechanism.mdx
Details in https://app.devrev.ai/devrev/works/ISS-146925
Do not want to encourage developers to log events. Instead noting the best practice.
> Convey proper logging practice in code sample

- fern/versions/public.yml
This commit fixes a mistake in a previous commit, which renamed
ADaaS to Airdrop, which resulted in breaking existing links.
https://app.devrev.ai/devrev/works/ISS-154205
> fix: ADaaS -> Airdrop import and hiding

- fern/docs/pages/plug-sdk/sdk-ios.mdx
This PR updates iOS SDK's minimum OS version requirement.
> [!IMPORTANT]
> **Check** the ***Hide whitespace*** option when reviewing.
/close ISS-159085
0%
> ISS-159085: Update the documentation

- fern/docs/pages/interact-agent.mdx
Resolving leftover comments from this PR: https://github.com/devrev/fern-api-docs/pull/174
- no-work-item
> fix: resolve comments from last PR of adding agents async API guide

- fern/docs/pages/plug-sdk/react-native.mdx
This PR updates the React Native SDK guide.
> ISS-160289: Update the React Native SDK guide

- fern/docs/pages/plug-sdk/ios/features.mdx
This PR updates the Fern documentation to include details about the useDefaultTheme flag. The new section demonstrates how to enable this flag to ensure the support feature always uses the default theme, regardless of the user’s system theme setting. This enhancement helps developers maintain consistent UI behavior across environments.
> ISS-167739: Update Fern to support use default theme flag in documentation

- fern/docs/pages/customization.mdx
https://app.devrev.ai/devrev/works/TKT-22694
> docs: update `stock_field_overrides` to keep the ordering consistent

- fern/docs/pages/airdrop/metadata-extraction.mdx
https://app.devrev.ai/devrev/works/ISS-153220
> docs: Add information about is loadable to metadata extraction

- fern/docs/pages/airdrop/extraction-phases.mdx
- fern/docs/pages/airdrop/initial-domain-mapping.mdx
- fern/docs/pages/airdrop/loading-phases.mdx
- fern/docs/pages/airdrop/manifest.mdx
- fern/docs/pages/airdrop/snap-in-template.mdx
https://app.devrev.ai/devrev/works/ISS-168649
> Update Airdrop documentation regarding IDM installation

- fern/docs/pages/airdrop/data-model/rich-text-fields.mdx
Clarifies that the `ref_type` in mention object should be the record type that was defined in external domain metadata.
https://app.devrev.ai/devrev/works/ISS-153220
> Clarify rich text description of mention object

- fern/docs/pages/sdks/web/ue-migration.mdx
removed session_recording_enabled in plug initialisation method for enabling session recording.
https://app.devrev.ai/devrev/works/ISS-178091
> changed the position of note

- fern/apis/beta/changelog/2025-06-02.md
- fern/apis/beta/openapi-beta.yaml
- fern/apis/public/changelog/2025-06-02.md
- fern/apis/public/openapi-public.yaml
- fern/fern.config.json
> chore: Update OpenAPI specs

- fern/apis/beta/openapi-beta.yaml
- fern/apis/public/openapi-public.yaml
- fern/docs/pages/create-accounts.mdx
- fern/docs/pages/custom-objects.mdx
- fern/docs/pages/customization.mdx
- fern/docs/pages/interact-agent.mdx
- fern/docs/pages/timeline-entries.mdx
- fern/docs/pages/webhooks.mdx
- fern/docs/pages/welcome.mdx
> chore: Include 'Bearer' in authorization header documentation

- fern/docs/pages/sdks/web/methods.mdx
Work item: https://app.devrev.ai/devrev/works/ISS-180501
> Cross-domain session tracking link

- fern/docs/pages/sdks/web/install.mdx
Work item: https://app.devrev.ai/devrev/works/ISS-172058
> Web SDK CSP URLs

- fern/apis/beta/generators.yml
- fern/apis/public/generators.yml
- fern/docs.yml
- fern/docs/pages/custom-objects.mdx
- fern/docs/pages/customization.mdx
- fern/versions/beta.yml
- fern/versions/public.yml
- Add `leaf_type_display_name` in custom object schema
- Document that dependent field expressions are binary
- Update supported operations in dependent field expressions
- s/`deprecated`/`is_deprecated` in schema deprecation example
- Document `unique_key`
https://app.devrev.ai/devrev/works/ISS-168821
> Make customization docs public

- custom-implementation/src/main.css
- custom-implementation/src/main.tsx
- fern/docs.yml
https://app.devrev.ai/devrev/works/TKT-25906
> fix: testing laptop screen for missing components

- fern/docs/pages/sdks/mobile/android/troubleshooting.mdx
This PR updates the troubleshooting guide with common proguard issues that our customers face. 
https://app.devrev.ai/devrev/works/ISS-190256
> ISS-190256: Update proguard troubleshooting guide
